{% set name = "pytest-raises" %}
{% set version = "0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f64a4dbcb5f89c100670fe83d87a5cd9d956586db461c5c628f7eb94b749c90b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=3.2.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_raises

about:
  home: https://github.com/Lemmons/pytest-raises
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: An implementation of pytest.raises as a pytest.mark fixture
  description: |
    Adds functionality for marking tests with a `pytest.mark.raises`
    fixture, which functions similarly to using `with pytest.raises`
  dev_url: https://github.com/Lemmons/pytest-raises

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
